database:
  path: "data/assistant.db"

ollama:
  base_url: "http://localhost:11434"
  timeout_seconds: 300

models:
  light_tier:
    - "phi3:3.8b"
  medium_tier:
    - "gemma2:9b"
    - "deepseek-coder:6.7b"
  heavy_tier:
    - "llama3.1:8b"
    - "gemma2:27b"
    - "deepseek-coder:33b"
  npu_tier:
    - "phi3:3.8b"
    - "gemma2:2b"