version: '3.8'

services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    gpus: all
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped

volumes:
  ollama: