version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ai_assistant_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu
      - cpu

  # CPU-only fallback for ollama
  ollama-cpu:
    image: ollama/ollama:latest
    container_name: ai_assistant_ollama_cpu
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    profiles:
      - cpu-only

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_assistant_backend
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/app/data
      - ./backend/config.yaml:/app/config.yaml:ro
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - RUST_LOG=info
      - DATABASE_PATH=/app/data/assistant.db
    depends_on:
      - ollama
    restart: unless-stopped
    profiles:
      - gpu
      - cpu

  backend-cpu:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_assistant_backend_cpu
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/app/data
      - ./backend/config.yaml:/app/config.yaml:ro
    environment:
      - OLLAMA_BASE_URL=http://ollama-cpu:11434
      - RUST_LOG=info
      - DATABASE_PATH=/app/data/assistant.db
    depends_on:
      - ollama-cpu
    restart: unless-stopped
    profiles:
      - cpu-only

volumes:
  ollama_data:
    driver: local
  backend_data:
    driver: local

networks:
  default:
    name: ai_assistant_network