name: Link Check

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: >
            --verbose --no-progress --max-redirects 5
            --exclude-path "frontend/node_modules" 
            --exclude-path ".git"
            --exclude-mail 
            "**/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
